### PR TITLE
data1.txt added

### PR DESCRIPTION
**Pull request by Aditya-Sawarkar**
abee yeee   yedhya..   approve kr mazi file

### CODE REVIEW

**Comment by Aditya-Sawarkar** [comment]
> you have to make some changes in it

i have no fucking time time to do that just approve by requst or go to fucking hell

**Review by itsofficialpawan — COMMENTED** [review]
ready to merge

**Comment by itsofficialpawan** [comment]
ready to merge

**Comment by itsofficialpawan** [comment]
> > you have to make some changes in it
> 
> i have no fucking time time to do that just approve by requst or go to fucking hell

i am your boss do what is says

**Review by itsofficialpawan — COMMENTED** [review]
done

**Pull request merged**
